version: "3.8"

x-superset-volumes: &superset-volumes
  - ./docker:/app/docker
  - superset_home:/app/superset_home

x-common-build: &common-build
  context: .
  target: dev
  cache_from:
    - apache/superset-cache:3.10-slim-bookworm

services:
  redis:
    image: redis:7
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data 
  superset:
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    build:
      <<: *common-build
    container_name: superset_app
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    user: "root"
    restart: always
    ports:
      - 8088:8088
    depends_on:
      superset-init:
        condition: service_completed_successfully
    volumes: *superset-volumes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      SUPERSET_DATABASE_URI: mysql+pymysql://root:root@host.docker.internal:3306/superset
      
  superset-init:
    container_name: superset_init
    build:
      <<: *common-build
    command: ["/app/docker/docker-init.sh"]
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    user: "root"
    depends_on:
      redis:
        condition: service_started
    volumes: *superset-volumes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      SUPERSET_DATABASE_URI: mysql+pymysql://root:root@host.docker.internal:3306/superset
    healthcheck:
      disable: true

  superset-worker:
    build:
      <<: *common-build
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    restart: always
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      SUPERSET_DATABASE_URI: mysql+pymysql://root:root@host.docker.internal:3306/superset
    healthcheck:
      test: ["CMD-SHELL", "celery -A superset.tasks.celery_app:app inspect ping -d celery@$$HOSTNAME"]

  superset-worker-beat:
    build:
      <<: *common-build
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file:
      - path: docker/.env
        required: true
      - path: docker/.env-local
        required: false
    restart: always
    depends_on:
      superset-init:
        condition: service_completed_successfully
    user: "root"
    volumes: *superset-volumes
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SUPERSET_LOG_LEVEL: "${SUPERSET_LOG_LEVEL:-info}"
      SUPERSET_DATABASE_URI: mysql+pymysql://root:root@host.docker.internal:3306/superset
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  redis:
    external: false